# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 18:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='data',
            field=models.DateField(default=datetime.date(2017, 3, 20)),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='nom',
            field=models.CharField(default=b'2017-03-20', max_length=200),
        ),
    ]
