# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 12:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productes', '0002_auto_20170320_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='data',
            field=models.DateField(default=datetime.date(2017, 3, 22)),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='nom',
            field=models.CharField(default=b'2017-03-22', max_length=200),
        ),
    ]
